### ISSUE TITLE
ShannonLoader extension not working.

### ISSUE THREAD

**Issue by r00tb3** [grant-h/ShannonBaseband#1] opened 2020-08-23 12:26 UTC
Hi @grant-h ,

I am trying to load the ShannonLoader extension into ghidra but it ain't working.

I am receiving the following error:
![image](https://user-images.githubusercontent.com/24567198/90978189-7c6bfc80-e569-11ea-9f6e-163295deb6fc.png)

I've tried copying the ShannonLoader into the Ghidra's Extensions folder but it didn't work either.

I am using the latest ghidra version: `ghidra_9.1.2_PUBLIC`

Awaiting your response.

Thanks.

**Comment by grant-h** [comment] 2020-08-23 18:12
What value did you set your `GHIDRA_INSTALL_DIR` to? Did the console have any errors? What system are you using GHIDRA on?

**Comment by r00tb3** [comment] 2020-08-24 06:02
> What value did you set your `GHIDRA_INSTALL_DIR` to? Did the console have any errors? What system are you using GHIDRA on?

My bad I didn't set the path for `GHIDRA_INSTALL_DIR`.

A very n00b question how do I set the PATH for the same?

**Comment by r00tb3** [comment] 2020-08-24 06:15
> What value did you set your `GHIDRA_INSTALL_DIR` to?

export GHIDRA_INSTALL_DIR=/home/user/Desktop/ghidra_9.1.2_PUBLIC/ 

> Did the console have any errors?

If you mean the Linux console while exporting the GHIDRA_INSTALL_DIR then no It didn't have any error.

> What system are you using GHIDRA on?

Lubuntu 18.04.1 x86_64

**Comment by grant-h** [comment] 2020-08-26 05:21
This doesn't make sense as the version should be picked up by the install dir environment variable. It's not hardcoded anywhere. Are you using the right Java version (11) in Gradle to compile? I can't reproduce this on my end (macOS)

**Comment by grant-h** [comment] 2020-09-30 08:35
Closing as cant reproduce.

**Closed by grant-h** 2020-09-30 08:35 UTC
